prompt_order = [
    "username",
    "hostname",
    "directory",
    "custom.git_simple",
    "git_state",
    "line_break",
    "character",
]

[directory]
prefix = ""
style = "bold white"

[custom.git_simple]
command = "starship-git-simple"
when = "true"
style = ""
